language: node_js
node_js:
  - 8.11.3
cache: yarn
script: 
  - yarn install --frozen-lockfile
  - yarn lint
  - printf -- "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - npm config set '//registry.npmjs.org/:_authToken' "${CIVAR_NPM_TOKEN}";
  - if [ "${TRAVIS_BRANCH}" = "master" ] && ! [ `printf -- "${TRAVIS_COMMIT_MESSAGE}" | grep "Publish"` ]; then
      git checkout ${TRAVIS_BRANCH};
      git reset --hard ${TRAVIS_COMMIT};
      git remote set-url origin ${CIVAR_GH_REPOSITORY_URL};
      npm config set '//registry.npmjs.org/:_authToken' "${CIVAR_NPM_TOKEN}";
      if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
        if [ -z "${TRAVIS_COMMIT_MESSAGE##*"[major release]"*}" ]; then
          LERNA_CD_VERSION='major';
        elif [ -z "${TRAVIS_COMMIT_MESSAGE##*"[minor release]"*}" ]; then
          LERNA_CD_VERSION='minor';
        else
          LERNA_CD_VERSION='patch';
        fi;
        lerna publish --yes --cd-version ${LERNA_CD_VERSION};
      fi;
    fi;